defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: junk-food-development

test:
  <<: *defaults
  database: junk-food-test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
